# Generated by Django 6.0.5 on 2026-06-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='sku',
        ),
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(default=343, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
