# Generated by Django 6.0.4 on 2026-06-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_code', models.CharField(max_length=50, unique=True)),
                ('plate_number', models.CharField(max_length=30)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('month', models.CharField(blank=True, max_length=7, null=True)),
                ('monthly_start_mileage', models.PositiveIntegerField(default=0)),
                ('monthly_end_mileage', models.PositiveIntegerField(default=0)),
                ('kt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('fuel_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oil_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('battery_health', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('assigned_driver', models.CharField(blank=True, max_length=100, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('REPAIR', 'In Repair'), ('OVERDUE', 'Overdue')], default='READY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet.company')),
            ],
        ),
    ]
