# Generated by Django 6.0.5 on 2026-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='status',
            new_name='ards_status',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='monthly_end_mileage',
            new_name='balance_service_km',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='monthly_start_mileage',
            new_name='current_km',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='next_service_date',
            new_name='insurance_upto',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='assigned_driver',
            new_name='model_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='battery_health',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_level',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='kt_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='month',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='oil_level',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_code',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='si_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_using_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
