# Generated by Django 6.0.5 on 2026-06-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_rename_status_vehicle_ards_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='model_name',
            new_name='model_year',
        ),
    ]
