# Generated by Django 6.0.5 on 2026-06-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('odometer_reading', models.PositiveIntegerField()),
                ('service_type', models.CharField(choices=[('ROUTINE', 'Routine Maintenance'), ('REPAIR', 'Repair'), ('BREAKDOWN', 'Breakdown'), ('ACCIDENT', 'Accident'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('work_performed', models.TextField(blank=True, null=True)),
                ('breakdown_details', models.TextField(blank=True, null=True)),
                ('accident_details', models.TextField(blank=True, null=True)),
                ('workshop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mechanic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('next_service_due_km', models.PositiveIntegerField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('vehicle_downtime_days', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.part')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='service.vehicleservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='service.vehicleservice')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.serviceitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='service.vehicleservice')),
            ],
        ),
    ]
