# Generated by Django 6.0.5 on 2026-06-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_remove_part_sku_part_part_number'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part'),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
