# Generated by Django 6.0.5 on 2026-06-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_servicepart_part_delete_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleserviceitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='vehicleserviceitem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='vehicleservice',
            name='mechanic_name',
        ),
        migrations.DeleteModel(
            name='ServiceItem',
        ),
        migrations.DeleteModel(
            name='VehicleServiceItem',
        ),
    ]
