# Generated by Django 6.0.5 on 2026-06-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_vehicleserviceitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicepart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
